site_url: https://florianschuttkowski.com
repo_url: https://github.com/flowinho/MKDocs-based-Blog
repo_name: flowinho/mkdocs-based-blog
site_name: Florian Schuttkowski
copyright: >
  Copyright &copy; 2023-2024 Florian Schuttkowski
plugins:
  - privacy
  - search
  - blog
  - tags:
      tags_file: tags.md
theme:
  name: material
  language: de
  icon:
    logo: material/application-braces-outline
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Zum hellen Design wechseln

      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: deep purple
        toggle:
          icon: material/weather-night
          name: Zum dunklen Design wechseln

      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: orange
        toggle: 
          icon: material/weather-sunny
          name: Zum automatischen Modus wechseln

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@flowinho
    - icon: fontawesome/brands/github
      link: https://github.com/flowinho
    - icon: fontawesome/brands/slack
      link: https://audiodump.de/slack
    - icon: fontawesome/solid/paper-plane
      link: mailto:mail@florianschuttkowski.com
        #  consent:
        #title: Cookies?
        #description: >-
        #Test

extra_css:
  - stylesheets/extra.css
